package entities;
// Generated Mar 22, 2014 4:52:46 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="ROLES"
    ,schema="PARKING"
)
public class Roles  implements java.io.Serializable {


     private BigDecimal roleId;
     private String roleName;
     private Clob description;
     private Set employeeses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(BigDecimal roleId, String roleName) {
        this.roleId = roleId;
        this.roleName = roleName;
    }
    public Roles(BigDecimal roleId, String roleName, Clob description, Set employeeses) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.description = description;
       this.employeeses = employeeses;
    }
   
     @Id 
    
    @Column(name="ROLE_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(BigDecimal roleId) {
        this.roleId = roleId;
    }
    
    @Column(name="ROLE_NAME", nullable=false, length=20)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
    @Column(name="DESCRIPTION")
    public Clob getDescription() {
        return this.description;
    }
    
    public void setDescription(Clob description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="roles")
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


