package entities;
// Generated Mar 22, 2014 4:52:46 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,schema="PARKING"
)
public class Users  implements java.io.Serializable {


     private BigDecimal userId;
     private String userName;
     private String email;
     private String password;
     private Date birthDate;
     private String gender;
     private BigDecimal phone;

    public Users() {
    }

	
    public Users(BigDecimal userId, String userName, String email, String password) {
        this.userId = userId;
        this.userName = userName;
        this.email = email;
        this.password = password;
    }
    public Users(BigDecimal userId, String userName, String email, String password, Date birthDate, String gender, BigDecimal phone) {
       this.userId = userId;
       this.userName = userName;
       this.email = email;
       this.password = password;
       this.birthDate = birthDate;
       this.gender = gender;
       this.phone = phone;
    }
   
     @Id 
    
    @Column(name="USER_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }
    
    @Column(name="USER_NAME", nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="EMAIL", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="PASSWORD", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="BIRTH_DATE", length=7)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    
    @Column(name="GENDER", length=7)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    
    @Column(name="PHONE", precision=22, scale=0)
    public BigDecimal getPhone() {
        return this.phone;
    }
    
    public void setPhone(BigDecimal phone) {
        this.phone = phone;
    }




}


