package pojos;
// Generated Mar 22, 2014 4:29:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdminsActionId generated by hbm2java
 */
@Embeddable
public class AdminsActionId  implements java.io.Serializable {


     private long adminId;
     private long employeeId;
     private Date actionDate;

    public AdminsActionId() {
    }

    public AdminsActionId(long adminId, long employeeId, Date actionDate) {
       this.adminId = adminId;
       this.employeeId = employeeId;
       this.actionDate = actionDate;
    }
   

    @Column(name="ADMIN_ID", nullable=false, precision=11, scale=0)
    public long getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(long adminId) {
        this.adminId = adminId;
    }

    @Column(name="EMPLOYEE_ID", nullable=false, precision=11, scale=0)
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }

    @Column(name="ACTION_DATE", nullable=false, length=7)
    public Date getActionDate() {
        return this.actionDate;
    }
    
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdminsActionId) ) return false;
		 AdminsActionId castOther = ( AdminsActionId ) other; 
         
		 return (this.getAdminId()==castOther.getAdminId())
 && (this.getEmployeeId()==castOther.getEmployeeId())
 && ( (this.getActionDate()==castOther.getActionDate()) || ( this.getActionDate()!=null && castOther.getActionDate()!=null && this.getActionDate().equals(castOther.getActionDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getAdminId();
         result = 37 * result + (int) this.getEmployeeId();
         result = 37 * result + ( getActionDate() == null ? 0 : this.getActionDate().hashCode() );
         return result;
   }   


}


