package pojos;
// Generated Mar 22, 2014 4:29:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name="EMPLOYEES"
    ,schema="PARKING"
)
public class Employees  implements java.io.Serializable {


     private long employeeId;
     private Roles roles;
     private Garage garage;
     private String firstName;
     private String lastName;
     private String email;
     private String password;
     private String gender;
     private Date birthDate;
     private Set adminsActionsForAdminId = new HashSet(0);
     private Set adminsActionsForEmployeeId = new HashSet(0);

    public Employees() {
    }

	
    public Employees(long employeeId, Roles roles, Garage garage, String firstName, String lastName, String email, String password) {
        this.employeeId = employeeId;
        this.roles = roles;
        this.garage = garage;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
    }
    public Employees(long employeeId, Roles roles, Garage garage, String firstName, String lastName, String email, String password, String gender, Date birthDate, Set adminsActionsForAdminId, Set adminsActionsForEmployeeId) {
       this.employeeId = employeeId;
       this.roles = roles;
       this.garage = garage;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.password = password;
       this.gender = gender;
       this.birthDate = birthDate;
       this.adminsActionsForAdminId = adminsActionsForAdminId;
       this.adminsActionsForEmployeeId = adminsActionsForEmployeeId;
    }
   
     @Id 
    
    @Column(name="EMPLOYEE_ID", unique=true, nullable=false, precision=11, scale=0)
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ROLE_ID", nullable=false)
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GARAGE_ID", nullable=false)
    public Garage getGarage() {
        return this.garage;
    }
    
    public void setGarage(Garage garage) {
        this.garage = garage;
    }
    
    @Column(name="FIRST_NAME", nullable=false, length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="LAST_NAME", nullable=false, length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="EMAIL", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="PASSWORD", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="GENDER", length=5)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="BIRTH_DATE", length=7)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="employeesByAdminId")
    public Set getAdminsActionsForAdminId() {
        return this.adminsActionsForAdminId;
    }
    
    public void setAdminsActionsForAdminId(Set adminsActionsForAdminId) {
        this.adminsActionsForAdminId = adminsActionsForAdminId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="employeesByEmployeeId")
    public Set getAdminsActionsForEmployeeId() {
        return this.adminsActionsForEmployeeId;
    }
    
    public void setAdminsActionsForEmployeeId(Set adminsActionsForEmployeeId) {
        this.adminsActionsForEmployeeId = adminsActionsForEmployeeId;
    }




}


