package pojos;
// Generated Mar 22, 2014 4:29:13 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Garage generated by hbm2java
 */
@Entity
@Table(name="GARAGE"
    ,schema="PARKING"
)
public class Garage  implements java.io.Serializable {


     private long garageId;
     private Map map;
     private String title;
     private String country;
     private String city;
     private BigDecimal slots;
     private BigDecimal doors;
     private BigDecimal lon;
     private BigDecimal lat;
     private Set employeeses = new HashSet(0);

    public Garage() {
    }

	
    public Garage(long garageId, BigDecimal lon, BigDecimal lat) {
        this.garageId = garageId;
        this.lon = lon;
        this.lat = lat;
    }
    public Garage(long garageId, Map map, String title, String country, String city, BigDecimal slots, BigDecimal doors, BigDecimal lon, BigDecimal lat, Set employeeses) {
       this.garageId = garageId;
       this.map = map;
       this.title = title;
       this.country = country;
       this.city = city;
       this.slots = slots;
       this.doors = doors;
       this.lon = lon;
       this.lat = lat;
       this.employeeses = employeeses;
    }
   
     @Id 
    
    @Column(name="GARAGE_ID", unique=true, nullable=false, precision=11, scale=0)
    public long getGarageId() {
        return this.garageId;
    }
    
    public void setGarageId(long garageId) {
        this.garageId = garageId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MAP_ID")
    public Map getMap() {
        return this.map;
    }
    
    public void setMap(Map map) {
        this.map = map;
    }
    
    @Column(name="TITLE", length=50)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="COUNTRY", length=50)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="CITY", length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="SLOTS", precision=22, scale=0)
    public BigDecimal getSlots() {
        return this.slots;
    }
    
    public void setSlots(BigDecimal slots) {
        this.slots = slots;
    }
    
    @Column(name="DOORS", precision=22, scale=0)
    public BigDecimal getDoors() {
        return this.doors;
    }
    
    public void setDoors(BigDecimal doors) {
        this.doors = doors;
    }
    
    @Column(name="LON", nullable=false, precision=22, scale=0)
    public BigDecimal getLon() {
        return this.lon;
    }
    
    public void setLon(BigDecimal lon) {
        this.lon = lon;
    }
    
    @Column(name="LAT", nullable=false, precision=22, scale=0)
    public BigDecimal getLat() {
        return this.lat;
    }
    
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="garage")
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


